/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MapRouteImport } from './routes/map'
import { Route as HostRouteImport } from './routes/host'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeekSlugRouteImport } from './routes/week.$slug'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedHostSubmitRouteImport } from './routes/_authenticated/host.submit'
import { Route as AuthenticatedHostDashboardRouteImport } from './routes/_authenticated/host.dashboard'
import { Route as AuthenticatedAdminQueueRouteImport } from './routes/_authenticated/admin.queue'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin.calendar'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin.admins'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin.users.$id'
import { Route as AuthenticatedAdminEventIdRouteImport } from './routes/_authenticated/admin.event.$id'
import { Route as ApiPublicEventIdIcsDoticsRouteImport } from './routes/api/public/event.$id.ics[.]ics'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekSlugRoute = WeekSlugRouteImport.update({
  id: '/week/$slug',
  path: '/week/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostSubmitRoute = AuthenticatedHostSubmitRouteImport.update({
  id: '/host/submit',
  path: '/host/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostDashboardRoute =
  AuthenticatedHostDashboardRouteImport.update({
    id: '/host/dashboard',
    path: '/host/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQueueRoute = AuthenticatedAdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventIdRoute =
  AuthenticatedAdminEventIdRouteImport.update({
    id: '/event/$id',
    path: '/event/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicEventIdIcsDoticsRoute =
  ApiPublicEventIdIcsDoticsRouteImport.update({
    id: '/api/public/event/$id/ics.ics',
    path: '/api/public/event/$id/ics.ics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/host': typeof HostRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor': typeof SponsorRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/event/$id': typeof EventIdRoute
  '/week/$slug': typeof WeekSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/host/dashboard': typeof AuthenticatedHostDashboardRoute
  '/host/submit': typeof AuthenticatedHostSubmitRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/event/$id': typeof AuthenticatedAdminEventIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/event/$id/ics.ics': typeof ApiPublicEventIdIcsDoticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/host': typeof HostRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor': typeof SponsorRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/event/$id': typeof EventIdRoute
  '/week/$slug': typeof WeekSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/host/dashboard': typeof AuthenticatedHostDashboardRoute
  '/host/submit': typeof AuthenticatedHostSubmitRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/event/$id': typeof AuthenticatedAdminEventIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/event/$id/ics.ics': typeof ApiPublicEventIdIcsDoticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/host': typeof HostRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor': typeof SponsorRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/event/$id': typeof EventIdRoute
  '/week/$slug': typeof WeekSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/queue': typeof AuthenticatedAdminQueueRoute
  '/_authenticated/host/dashboard': typeof AuthenticatedHostDashboardRoute
  '/_authenticated/host/submit': typeof AuthenticatedHostSubmitRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/event/$id': typeof AuthenticatedAdminEventIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/event/$id/ics.ics': typeof ApiPublicEventIdIcsDoticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/calendar'
    | '/host'
    | '/map'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sponsor'
    | '/unsubscribe'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/email/unsubscribe'
    | '/event/$id'
    | '/week/$slug'
    | '/.lovable/oauth/consent'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/calendar'
    | '/admin/queue'
    | '/host/dashboard'
    | '/host/submit'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/admin/event/$id'
    | '/admin/users/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/event/$id/ics.ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/calendar'
    | '/host'
    | '/map'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sponsor'
    | '/unsubscribe'
    | '/.well-known/oauth-protected-resource'
    | '/email/unsubscribe'
    | '/event/$id'
    | '/week/$slug'
    | '/.lovable/oauth/consent'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/calendar'
    | '/admin/queue'
    | '/host/dashboard'
    | '/host/submit'
    | '/lovable/email/suppression'
    | '/admin'
    | '/admin/event/$id'
    | '/admin/users/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/event/$id/ics.ics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/calendar'
    | '/host'
    | '/map'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sponsor'
    | '/unsubscribe'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/email/unsubscribe'
    | '/event/$id'
    | '/week/$slug'
    | '/.lovable/oauth/consent'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/queue'
    | '/_authenticated/host/dashboard'
    | '/_authenticated/host/submit'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/event/$id'
    | '/_authenticated/admin/users/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/event/$id/ics.ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  HostRoute: typeof HostRoute
  MapRoute: typeof MapRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorRoute: typeof SponsorRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EventIdRoute: typeof EventIdRoute
  WeekSlugRoute: typeof WeekSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicEventIdIcsDoticsRoute: typeof ApiPublicEventIdIcsDoticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week/$slug': {
      id: '/week/$slug'
      path: '/week/$slug'
      fullPath: '/week/$slug'
      preLoaderRoute: typeof WeekSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host/submit': {
      id: '/_authenticated/host/submit'
      path: '/host/submit'
      fullPath: '/host/submit'
      preLoaderRoute: typeof AuthenticatedHostSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host/dashboard': {
      id: '/_authenticated/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof AuthenticatedHostDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/queue': {
      id: '/_authenticated/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AuthenticatedAdminQueueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/event/$id': {
      id: '/_authenticated/admin/event/$id'
      path: '/event/$id'
      fullPath: '/admin/event/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/event/$id/ics.ics': {
      id: '/api/public/event/$id/ics.ics'
      path: '/api/public/event/$id/ics.ics'
      fullPath: '/api/public/event/$id/ics.ics'
      preLoaderRoute: typeof ApiPublicEventIdIcsDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminQueueRoute: typeof AuthenticatedAdminQueueRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventIdRoute: typeof AuthenticatedAdminEventIdRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminQueueRoute: AuthenticatedAdminQueueRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEventIdRoute: AuthenticatedAdminEventIdRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHostDashboardRoute: typeof AuthenticatedHostDashboardRoute
  AuthenticatedHostSubmitRoute: typeof AuthenticatedHostSubmitRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHostDashboardRoute: AuthenticatedHostDashboardRoute,
  AuthenticatedHostSubmitRoute: AuthenticatedHostSubmitRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  HostRoute: HostRoute,
  MapRoute: MapRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorRoute: SponsorRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EventIdRoute: EventIdRoute,
  WeekSlugRoute: WeekSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicEventIdIcsDoticsRoute: ApiPublicEventIdIcsDoticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
